import { relative, isAbsolute } from "node:path";
import type { ReviewReport, UXIssue, IssueSeverity } from "../types.js";

const SEVERITY_ORDER: Record<IssueSeverity, number> = { critical: 0, warning: 1, suggestion: 2 };
const SEVERITY_LABEL: Record<IssueSeverity, string> = {
  critical: "🚨 critical",
  warning: "⚠️ warning",
  suggestion: "💡 suggestion",
};

interface MarkdownOptions {
  embedScreenshots?: boolean;
  reportDir?: string;
}

function severityBadge(s: IssueSeverity): string {
  return SEVERITY_LABEL[s];
}

function relPath(path: string | undefined, reportDir: string | undefined): string | undefined {
  if (!path) return undefined;
  if (!reportDir) return path;
  if (!isAbsolute(path)) return path;
  return relative(reportDir, path) || path;
}

function sortIssues(issues: UXIssue[]): UXIssue[] {
  return [...issues].sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]);
}

function renderIssue(issue: UXIssue): string {
  return `- **[${severityBadge(issue.severity)}] ${issue.category}** — _${issue.location || "unknown location"}_
  - **Issue:** ${issue.issue}
  - **Why it matters:** ${issue.why_it_matters}
  - **Fix:** ${issue.fix}`;
}

export function renderMarkdownReport(report: ReviewReport, opts: MarkdownOptions = {}): string {
  const lines: string[] = [];
  lines.push(`# MotionLint Report`);
  lines.push("");
  lines.push(`- **URL:** ${report.url}`);
  lines.push(`- **Generated:** ${report.timestamp}`);
  lines.push(`- **Provider:** ${report.provider} (${report.model})`);
  lines.push(`- **Aggregate score:** ${report.aggregate_score}/10`);
  lines.push(`- **Issues:** 🚨 ${report.critical_count} critical · ⚠️ ${report.warning_count} warning · 💡 ${report.suggestion_count} suggestion`);
  lines.push("");

  if (report.analyses.length === 0) {
    lines.push("> No analyses produced.");
    return lines.join("\n");
  }

  for (const entry of report.analyses) {
    const { capture, analysis } = entry;
    lines.push(`## Viewport: ${capture.viewport.name} (${capture.viewport.width}×${capture.viewport.height})`);
    lines.push("");
    lines.push(`**Score:** ${analysis.overall_score}/10`);
    lines.push("");
    if (analysis.summary) {
      lines.push(`> ${analysis.summary.replace(/\n+/g, " ")}`);
      lines.push("");
    }

    const screenshotRel = relPath(capture.screenshotPath, opts.reportDir);
    if (opts.embedScreenshots && screenshotRel) {
      lines.push(`![${capture.viewport.name} screenshot](${screenshotRel})`);
      lines.push("");
    } else if (screenshotRel) {
      lines.push(`Screenshot: \`${screenshotRel}\``);
      lines.push("");
    }

    const videoRel = relPath(capture.videoPath, opts.reportDir);
    if (videoRel) {
      lines.push(`Video: \`${videoRel}\``);
      lines.push("");
    }

    if (analysis.issues.length === 0) {
      lines.push("_No issues identified at this viewport._");
      lines.push("");
    } else {
      lines.push(`### Issues (${analysis.issues.length})`);
      lines.push("");
      for (const issue of sortIssues(analysis.issues)) {
        lines.push(renderIssue(issue));
        lines.push("");
      }
    }

    if (analysis.strengths.length > 0) {
      lines.push(`### Strengths`);
      lines.push("");
      for (const s of analysis.strengths) lines.push(`- ${s}`);
      lines.push("");
    }
  }

  lines.push(`---`);
  lines.push(`Generated by [MotionLint](https://github.com/bobaba99/motionlint) — AI design review in your terminal.`);
  return lines.join("\n");
}
